# Generated by Django 2.1.2 on 2018-10-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeKey',
            fields=[
                ('attr_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attr_name', models.CharField(max_length=30)),
                ('sort', models.IntegerField()),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('value_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value_name', models.CharField(max_length=30)),
                ('sort', models.IntegerField()),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
                ('key_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.AttributeKey')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=30)),
                ('parent_id', models.CharField(max_length=100)),
                ('sort', models.IntegerField()),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=30)),
                ('thumb_url', models.CharField(max_length=100)),
                ('img_urls', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('prod_attr', models.CharField(max_length=500)),
                ('sort', models.IntegerField()),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('ProdAttr_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sort', models.IntegerField()),
                ('created_time', models.DateField()),
                ('updated_time', models.DateField()),
                ('attr_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AttributeKey')),
                ('attr_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AttributeValue')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='attributekey',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
    ]
