# Generated by Django 2.1.2 on 2018-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekey',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attributekey',
            name='updated_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='updated_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
