# Generated by Django 2.1.2 on 2018-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181028_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='ProdAttr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
